### ISSUE TITLE
Explore using S3 Transfer Manager

### ISSUE THREAD

**Issue by cobookman** [aws/amazon-s3-plugin-for-pytorch#14]
AWS SDK provides a S3 Transfer Manager that handles s3 copy to memory operations. Looks like the library is only making use of the TransferManager when downloading a multi-part object..

This library seems to use just 1 thread for downloading non-multipart objects. And if the object is large enough, having multiple threads downloading different chunks of the object would improve performance. It might pay to have both multipart and non-multipart objects use the TransferManager.

https://github.com/aws/amazon-s3-plugin-for-pytorch/blob/38284c8a5e92be3bbf47b08e8c90d94be0cb79e7/awsio/csrc/io/s3/s3_io.cpp#L163

**Comment by ydaiming** [comment]
@cobookman 

We're upstreaming the *amazon-s3-plugin-for-pytorch* into the *torchdata* package (https://github.com/pytorch/data/pull/165).
We're dropping support for this plugin.

For you question, I believe the S3 Transfer Manager or multi-part downloaing is always use, unless directed otherwise:

https://github.com/aws/amazon-s3-plugin-for-pytorch/blob/ed89987aa7c7b824534c2f9310906a278cf75a88/awsio/csrc/io/s3/s3_io.cpp#L258
