### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by anmoldhingra1** [aws/amazon-s3-plugin-for-pytorch#19]
Please provide clear documentation to install on different cluster than AWS specific. I guess this plugin would be helpful for every individual who is consuming data from s3. 

Need a documentation w,r,t dockerHub docker or a python package to install this.

**Comment by rehno-lindeque** [comment]
Just in case it helps anyone, since there are so many "installation" issues on this repo: 

I've made a work-in-progress package for the [nix package manager](https://nixos.org/download.html#nix-install-linux) for my personal use. The PR is here: 

https://github.com/NixOS/nixpkgs/pull/152465/files

However, fair warning: you probably need to be a nix expert to use it for now. (It works for me personally but I don't want to make an effort to get it merged right now, esp since there's [no official release to reference](https://github.com/NixOS/nixpkgs/pull/152465/files#r790174297).)

**Comment by ydaiming** [comment]
Hi @anmoldhingra1 , I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
