### ISSUE TITLE
Does it work for S3 protocol of Minio or Ceph

### ISSUE THREAD

**Issue by austingg** [aws/amazon-s3-plugin-for-pytorch#9]
Does it work for S3 protocol of Minio or Ceph ？

**Comment by ydaiming** [comment]
@austingg 

We're upstreaming the amazon-s3-plugin-for-pytorch into the torchdata package (https://github.com/pytorch/data/pull/165).
We're dropping support for this plugin.

I believe your issue is relevant to this issue about `export S3_ENDPOINT_URL=your_s3_endpoint`: https://github.com/aws/amazon-s3-plugin-for-pytorch/issues/8
